export const PAGE_ID = {
    INDEX: 'INDEX',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    CREATE_REPOSITORY: 'CREATE_REPOSITORY',
    PERSONAL_CENTER: 'PERSONAL_CENTER',
    REPOSITORY: 'REPOSITORY',
};